vizzys fgd update (except icons)
mapbase-source/source-fgds pull request #4
Opened 2024-12-04 09:31 UTC by meatspace

This is based on the "mapbase" branch of the mapbase-source/source-fgds repo

I did not add custom Icons/entity model helpers in this specific commit. 

I did not include the custom soundscapes lines I added. 

"Touch Opens" flag for the base door class was changed from 1 to 0, not sure is that's intentional on your part but imo its better off by default.

Whats new?

many missing inputs/outputs
many improved entity descriptions
many entity helper lines/spheres
many typo fixes

2025-01-14 14:24 UTC, Blixibon requested changes
I was a bit confused to see some of Mapbase v7.3's FGD changes already in here. For future reference, I was planning on committing those myself later. Adding them like this ahead of time can lead to merge conflicts due to them being added at the same time through separate commits.

I have some questions about the content in this branch, although I would be interested in integrating this for v8.0 with some additional changes.

2025-01-14 14:24 UTC, Blixibon commented on base.fgd
> +// start commentary section added by vizzys
Why add the commentary entities?

2025-01-14 14:24 UTC, Blixibon commented on base.fgd
> +	input GetFMod(float) : "Outputs the current modulation settings in console."
This does not take a float input

2025-01-14 14:24 UTC, Blixibon commented on halflife2.fgd
> +		"weapon_citizenpackage" : "Citizen Package  (Ration)"
```suggestion
		"weapon_citizenpackage" : "Citizen Package (Ration)"
```

2025-01-14 14:24 UTC, Blixibon commented on halflife2.fgd
> +		4 : "Unique (Set a particular model with Model)"
Different description compared to npc_citizen above

2025-01-14 14:24 UTC, Blixibon commented on halflife2.fgd
> +	]
Why is this 0 by default?

2025-01-14 22:05 UTC, meatspace commented on halflife2.fgd
> +	]
I just assumed off would be the more likely choice when manually placing jeep/buggy in hammer. Ill change it to 1 I suppose

2025-01-14 22:07 UTC, meatspace commented on base.fgd
> +// start commentary section added by vizzys
i figured someone would use it, but I dont have the information you have about the missing other modes (image, etc) and I notice now I forgot to remove my custom icon here so Ill get rid of it.

2025-01-14 22:07 UTC, meatspace commented on halflife2.fgd
> +		4 : "Unique (Set a particular model with Model)"
will fix

2025-01-14 22:17 UTC, meatspace commented
I think I fixed it, feel free to add more comments and such. Anything can be edited to your hearts desire ofc, especially descriptions which some are worded in a terse way to not exceed the 128 character string limitation

2025-01-18 08:34 UTC, meatspace commented
merge conflicts suck u were right... iam bad at computer
if you cant salvage this just let me know, ill resubmit a new PR instead.

anyway, if you want this to be some big update thing I think including the custom icons I made would be good

I keep that all in a seperate repo (havent update it for 7.3 yet)
[(https://github.com/meatspace/vizzys_fgds)](https://github.com/meatspace/vizzys_fgds)

2026-02-21 03:47 UTC, closed without merging